# Generated by Django 5.0.6 on 2024-06-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
                ('category_code', models.CharField(max_length=20)),
                ('category_name', models.CharField(max_length=30)),
                ('subcategory_code', models.CharField(max_length=20)),
                ('subcategory_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=30)),
                ('telegram_id', models.BigIntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
